### ISSUE TITLE
cURL error 60: SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by sjea** [alamirault/fftt-api-src#20]
Depuis ce matin, j'obtiens cette erreur lors de l'appel de l'API FFTT via ce projet (hier soir tout fonctionnait correctement).

**Comment by alamirault** [comment]
Est-ce revenu dans l'ordre ?

Si non, est-ce qu'en modifiant la constante https://github.com/alamirault/fftt-api-src/blob/main/src/Service/UriGenerator.php#L7 en remplaçant `http` par `https` cela corrige le soucis ?

**Comment by sjea** [comment]
La FFTT m'avait indiqué qu'il y avait un problème sur leur certificat depuis ce matin donc j'attendais patiemment.

Mais en faisant la modification que vous venez de proposer, tout est revenu dans l'ordre. Merci très sincèrement.
